# **Projet 3 - Prédiction de la consommation énergétique des bâtiments de Seattle**

 * Prédire la consommation énergétique des bâtiments non résidentiels de Seattle à partir de leurs caractéristiques structurelles.
 * Réaliser une analyse exploratoire afin d'identifier les principales tendances et anomalies des données.
 * Comparer plusieurs modèles de régression supervisée pour sélectionner le plus performant.
 * Identifier les variables ayant le plus d'influence sur la consommation énergétique.*

## **Contexte** 

* La ville de Seattle souhaite atteindre la neutralité carbone d'ici 2050.
* Les relevés énergétiques des bâtiments sont coûteux à réaliser et ne sont pas disponibles pour l'ensemble du parc immobilier.
* L'objectif est d'utiliser les données collectées en 2016 afin d'estimer la consommation énergétique des bâtiments non encore mesurés.*

## **Objectfs Data** 
- **Comprendre le jeu de données :** analyser la structure, les types de variables, les valeurs manquantes et la qualité des données.
- **Nettoyer et préparer les données :** sélectionner les bâtiments non résidentiels, traiter les incohérences et préparer les variables pour la modélisation.
- **Réaliser une analyse exploratoire (EDA) :** identifier les distributions, les corrélations et les facteurs susceptibles d'influencer la consommation énergétique.
- **Construire et comparer plusieurs modèles de régression** afin de prédire la consommation énergétique des bâtiments.
- **Interpréter le modèle retenu :** analyser l'importance des variables explicatives et identifier les principaux facteurs influençant la consommation énergétique.

## **Partie 1**

### **Étape 1- Réalisez une analyse exploratoire**

A réaliser : 
- Une analyse descriptive des données, y compris une explication du sens des colonnes gardées, des arguments derrière la suppression de lignes ou de colonnes, des statistiques descriptives et des visualisations pertinentes.

Qelques pistes d'analyse :

* Identifier les colonnes avec une majorité de valeurs manquantes ou constantes en utilisant la méthode value_counts() de Pandas
* Mettre en evidence les différences entre les immeubles mono et multi-usages
* Utiliser des pairplots et des boxplots pour faire ressortir les outliers ou des batiments avec des valeurs peu cohérentes d'un point de vue métier 

Pour vous inspirer, ou comprendre l'esprit recherché dans une analyse exploratoire, vous pouvez consulter ce notebook en ligne : https://www.kaggle.com/code/pmarcelino/comprehensive-data-exploration-with-python. Il ne s'agit pas d'un modèle à suivre à la lettre ni d'un template d'analyses attendues pour ce projet.

#### **Importation des librairies**

In [29]:
#importation des librairies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Importation des librairies OK")

Importation des librairies OK

#### **Importation du Dataset**

In [30]:
df_building_consumption = pd.read_csv("../data/2016_Building_Energy_Benchmarking.csv")

#### **Analyse Exploratoire**

##### **Standardisation des colonnes**

> * Adaptation et standardisation des noms de colonnes conformément aux bonnes pratiques.

In [31]:
# visualisation des colonnes de la base de données
df_building_consumption.columns

Index(['OSEBuildingID', 'DataYear', 'BuildingType', 'PrimaryPropertyType',
       'PropertyName', 'Address', 'City', 'State', 'ZipCode',
       'TaxParcelIdentificationNumber', 'CouncilDistrictCode', 'Neighborhood',
       'Latitude', 'Longitude', 'YearBuilt', 'NumberofBuildings',
       'NumberofFloors', 'PropertyGFATotal', 'PropertyGFAParking',
       'PropertyGFABuilding(s)', 'ListOfAllPropertyUseTypes',
       'LargestPropertyUseType', 'LargestPropertyUseTypeGFA',
       'SecondLargestPropertyUseType', 'SecondLargestPropertyUseTypeGFA',
       'ThirdLargestPropertyUseType', 'ThirdLargestPropertyUseTypeGFA',
       'YearsENERGYSTARCertified', 'ENERGYSTARScore', 'SiteEUI(kBtu/sf)',
       'SiteEUIWN(kBtu/sf)', 'SourceEUI(kBtu/sf)', 'SourceEUIWN(kBtu/sf)',
       'SiteEnergyUse(kBtu)', 'SiteEnergyUseWN(kBtu)', 'SteamUse(kBtu)',
       'Electricity(kWh)', 'Electricity(kBtu)', 'NaturalGas(therms)',
       'NaturalGas(kBtu)', 'DefaultData', 'Comments', 'ComplianceStatus',
       'Outlier', 'TotalGHGEmissions', 'GHGEmissionsIntensity'],
      dtype='str')

In [32]:
#Adaptation et standardisation des noms de colonnes conformément aux bonnes pratiques

df_building_consumption.columns = (
    df_building_consumption.columns
    .str.lower()                  # minúscules
    .str.strip()                  # remotion des espaces en début et fin de chaîne
    .str.replace(" ", "_")        # espace -> _
    .str.replace("-", "_")        # hífen -> _

)

In [33]:
# visualisation des colonnes après adaptation et standardisation

df_building_consumption.columns

Index(['osebuildingid', 'datayear', 'buildingtype', 'primarypropertytype',
       'propertyname', 'address', 'city', 'state', 'zipcode',
       'taxparcelidentificationnumber', 'councildistrictcode', 'neighborhood',
       'latitude', 'longitude', 'yearbuilt', 'numberofbuildings',
       'numberoffloors', 'propertygfatotal', 'propertygfaparking',
       'propertygfabuilding(s)', 'listofallpropertyusetypes',
       'largestpropertyusetype', 'largestpropertyusetypegfa',
       'secondlargestpropertyusetype', 'secondlargestpropertyusetypegfa',
       'thirdlargestpropertyusetype', 'thirdlargestpropertyusetypegfa',
       'yearsenergystarcertified', 'energystarscore', 'siteeui(kbtu/sf)',
       'siteeuiwn(kbtu/sf)', 'sourceeui(kbtu/sf)', 'sourceeuiwn(kbtu/sf)',
       'siteenergyuse(kbtu)', 'siteenergyusewn(kbtu)', 'steamuse(kbtu)',
       'electricity(kwh)', 'electricity(kbtu)', 'naturalgas(therms)',
       'naturalgas(kbtu)', 'defaultdata', 'comments', 'compliancestatus',
       'outlier', 'totalghgemissions', 'ghgemissionsintensity'],
      dtype='str')

##### **Dimensions**

In [37]:
print("La base de données contient", df_building_consumption.shape[0], "lignes et", df_building_consumption.shape[1], "colonnes.")

La base de données contient 3376 lignes et 46 colonnes.

In [35]:
# On regarde comment un batiment est défini dans ce jeu de données 

df_building_consumption.head()

,osebuildingid,datayear,buildingtype,primarypropertytype,propertyname,address,city,state,zipcode,taxparcelidentificationnumber,...,electricity(kwh),electricity(kbtu),naturalgas(therms),naturalgas(kbtu),defaultdata,comments,compliancestatus,outlier,totalghgemissions,ghgemissionsintensity
0,1,2016,NonResidential,Hotel,Mayflower park hotel,405 Olive way,Seattle,WA,98101.0,0659000030,...,1.156514e+06,3946027.0,12764.52930,1276453.0,False,NaN,Compliant,NaN,249.98,2.83
1,2,2016,NonResidential,Hotel,Paramount Hotel,724 Pine street,Seattle,WA,98101.0,0659000220,...,9.504252e+05,3242851.0,51450.81641,5145082.0,False,NaN,Compliant,NaN,295.86,2.86
2,3,2016,NonResidential,Hotel,5673-The Westin Seattle,1900 5th Avenue,Seattle,WA,98101.0,0659000475,...,1.451544e+07,49526664.0,14938.00000,1493800.0,False,NaN,Compliant,NaN,2089.28,2.19
3,5,2016,NonResidential,Hotel,HOTEL MAX,620 STEWART ST,Seattle,WA,98101.0,0659000640,...,8.115253e+05,2768924.0,18112.13086,1811213.0,False,NaN,Compliant,NaN,286.43,4.67
4,8,2016,NonResidential,Hotel,WARWICK SEATTLE HOTEL (ID8),401 LENORA ST,Seattle,WA,98121.0,0659000970,...,1.573449e+06,5368607.0,88039.98438,8803998.0,False,NaN,Compliant,NaN,505.01,2.88

In [36]:
# Aperçu derniéres 5 lignes

df_building_consumption.tail()

,osebuildingid,datayear,buildingtype,primarypropertytype,propertyname,address,city,state,zipcode,taxparcelidentificationnumber,...,electricity(kwh),electricity(kbtu),naturalgas(therms),naturalgas(kbtu),defaultdata,comments,compliancestatus,outlier,totalghgemissions,ghgemissionsintensity
3371,50222,2016,Nonresidential COS,Office,Horticulture building,1600 S Dakota St,Seattle,WA,NaN,1624049080,...,153655.0000,5.242709e+05,3254.750244,3.254750e+05,True,NaN,Error - Correct Default Data,NaN,20.94,1.70
3372,50223,2016,Nonresidential COS,Other,International district/Chinatown CC,719 8th Ave S,Seattle,WA,NaN,3558300000,...,116221.0000,3.965461e+05,5537.299805,5.537300e+05,False,NaN,Compliant,NaN,32.17,2.01
3373,50224,2016,Nonresidential COS,Other,Queen Anne Pool,1920 1st Ave W,Seattle,WA,NaN,1794501150,...,525251.6875,1.792159e+06,39737.390630,3.973739e+06,False,NaN,Compliant,NaN,223.54,16.99
3374,50225,2016,Nonresidential COS,Mixed Use Property,South Park Community Center,8319 8th Ave S,Seattle,WA,NaN,7883603155,...,102248.0000,3.488702e+05,3706.010010,3.706010e+05,False,NaN,Compliant,NaN,22.11,1.57
3375,50226,2016,Nonresidential COS,Mixed Use Property,Van Asselt Community Center,2820 S Myrtle St,Seattle,WA,NaN,7857002030,...,126774.3984,4.325542e+05,7203.419922,7.203420e+05,False,NaN,Compliant,NaN,41.27,2.26

> * Les cinq premiers et 5 derniéres enregistrements correspondent à des hôtels situés à Seattle (WA) en 2016. 
> * Ils illustrent les principales variables du jeu de données : localisation, caractéristiques du bâtiment, consommation énergétique et émissions de gaz à effet de serre.

##### **Types de données**

In [50]:
# Types de données
df_building_consumption.dtypes

osebuildingid                        int64
datayear                             int64
buildingtype                           str
primarypropertytype                    str
propertyname                           str
address                                str
city                                   str
state                                  str
zipcode                            float64
taxparcelidentificationnumber          str
councildistrictcode                  int64
neighborhood                           str
latitude                           float64
longitude                          float64
yearbuilt                            int64
numberofbuildings                  float64
numberoffloors                       int64
propertygfatotal                     int64
propertygfaparking                   int64
propertygfabuilding(s)               int64
listofallpropertyusetypes              str
largestpropertyusetype                 str
largestpropertyusetypegfa          float64
secondlargestpropertyusetype           str
secondlargestpropertyusetypegfa    float64
thirdlargestpropertyusetype            str
thirdlargestpropertyusetypegfa     float64
yearsenergystarcertified            object
energystarscore                    float64
siteeui(kbtu/sf)                   float64
siteeuiwn(kbtu/sf)                 float64
sourceeui(kbtu/sf)                 float64
sourceeuiwn(kbtu/sf)               float64
siteenergyuse(kbtu)                float64
siteenergyusewn(kbtu)              float64
steamuse(kbtu)                     float64
electricity(kwh)                   float64
electricity(kbtu)                  float64
naturalgas(therms)                 float64
naturalgas(kbtu)                   float64
defaultdata                           bool
comments                           float64
compliancestatus                       str
outlier                                str
totalghgemissions                  float64
ghgemissionsintensity              float64
dtype: object

##### **Doublons**

In [63]:
# Verification des doublons dans le jeu de données

df_building_consumption.duplicated().sum()

np.int64(0)

> **Observation :** 

> * Il n'y a pas de doublons

In [52]:
df_building_consumption.shape

(3376, 46)

##### **Valeurs manquantes**

In [61]:
# identification des valeurs manquantes

for col in df_building_consumption.columns:
    print(f"\n--- {col} ---")
    print(df_building_consumption[col].value_counts(dropna=False).head())

--- osebuildingid ---
osebuildingid
1    1
2    1
3    1
5    1
8    1
Name: count, dtype: int64

--- datayear ---
datayear
2016    3376
Name: count, dtype: int64

--- buildingtype ---
buildingtype
NonResidential          1460
Multifamily LR (1-4)    1018
Multifamily MR (5-9)     580
Multifamily HR (10+)     110
SPS-District K-12         98
Name: count, dtype: int64

--- primarypropertytype ---
primarypropertytype
Low-Rise Multifamily           987
Mid-Rise Multifamily           564
Small- and Mid-Sized Office    293
Other                          256
Warehouse                      187
Name: count, dtype: int64

--- propertyname ---
propertyname
Northgate Plaza            3
Lakeview                   2
South Park                 2
Garden Court Apartments    2
Central Park               2
Name: count, dtype: int64

--- address ---
address
2600 SW Barton St              4
2203 Airport Way S             4
309 South Cloverdale Street    4
500 5TH AVE                    2
3613 4th Ave S                 2
Name: count, dtype: int64

--- city ---
city
Seattle    3376
Name: count, dtype: int64

--- state ---
state
WA    3376
Name: count, dtype: int64

--- zipcode ---
zipcode
98109.0    294
98104.0    251
98122.0    243
98101.0    230
98105.0    191
Name: count, dtype: int64

--- taxparcelidentificationnumber ---
taxparcelidentificationnumber
1625049001    8
0002400002    5
3224049012    5
0925049346    5
3624039009    4
Name: count, dtype: int64

--- councildistrictcode ---
councildistrictcode
7    1037
3     596
2     509
4     367
5     338
Name: count, dtype: int64

--- neighborhood ---
neighborhood
DOWNTOWN                 573
EAST                     453
MAGNOLIA / QUEEN ANNE    423
GREATER DUWAMISH         375
NORTHEAST                280
Name: count, dtype: int64

--- latitude ---
latitude
47.66246    9
47.61598    7
47.62208    6
47.62395    5
47.52549    5
Name: count, dtype: int64

--- longitude ---
longitude
-122.29898    8
-122.35398    7
-122.33379    6
-122.33369    6
-122.32468    6
Name: count, dtype: int64

--- yearbuilt ---
yearbuilt
2000    72
1989    67
2014    67
2008    66
1999    64
Name: count, dtype: int64

--- numberofbuildings ---
numberofbuildings
1.0    3175
0.0      92
2.0      37
3.0      22
4.0      12
Name: count, dtype: int64

--- numberoffloors ---
numberoffloors
3    692
4    692
1    466
2    439
6    306
Name: count, dtype: int64

--- propertygfatotal ---
propertygfatotal
36000    9
25920    8
21600    7
28800    7
24000    6
Name: count, dtype: int64

--- propertygfaparking ---
propertygfaparking
0         2872
13320        3
30000        2
20416        2
100176       2
Name: count, dtype: int64

--- propertygfabuilding(s) ---
propertygfabuilding(s)
36000    9
25920    8
21600    7
28800    7
24000    6
Name: count, dtype: int64

--- listofallpropertyusetypes ---
listofallpropertyusetypes
Multifamily Housing             866
Multifamily Housing, Parking    464
Office                          139
K-12 School                     135
Office, Parking                 120
Name: count, dtype: int64

--- largestpropertyusetype ---
largestpropertyusetype
Multifamily Housing           1667
Office                         498
Non-Refrigerated Warehouse     199
K-12 School                    139
Other                          102
Name: count, dtype: int64

--- largestpropertyusetypegfa ---
largestpropertyusetypegfa
NaN        20
22000.0     9
24000.0     9
30000.0     8
21600.0     8
Name: count, dtype: int64

--- secondlargestpropertyusetype ---
secondlargestpropertyusetype
NaN             1697
Parking          976
Office           215
Retail Store     155
Other             59
Name: count, dtype: int64

--- secondlargestpropertyusetypegfa ---
secondlargestpropertyusetypegfa
NaN        1697
0.0         126
5000.0       14
15000.0      12
7200.0       12
Name: count, dtype: int64

--- thirdlargestpropertyusetype ---
thirdlargestpropertyusetype
NaN             2780
Retail Store     110
Office           105
Parking           71
Restaurant        56
Name: count, dtype: int64

--- thirdlargestpropertyusetypegfa ---
thirdlargestpropertyusetypegfa
NaN       2780
0.0         48
6000.0       7
5000.0       6
3000.0       5
Name: count, dtype: int64

--- yearsenergystarcertified ---
yearsenergystarcertified
NaN         3257
2016          14
20172016       8
2017           7
2014           6
Name: count, dtype: int64

--- energystarscore ---
energystarscore
NaN      843
100.0    109
98.0      72
96.0      64
89.0      58
Name: count, dtype: int64

--- siteeui(kbtu/sf) ---
siteeui(kbtu/sf)
28.799999    17
24.700001    17
0.000000     16
24.200001    16
32.000000    15
Name: count, dtype: int64

--- siteeuiwn(kbtu/sf) ---
siteeuiwn(kbtu/sf)
0.000000     29
29.500000    17
30.799999    15
31.600000    14
30.200001    14
Name: count, dtype: int64

--- sourceeui(kbtu/sf) ---
sourceeui(kbtu/sf)
0.000000     24
68.099998     9
83.699997     9
NaN           9
94.099998     8
Name: count, dtype: int64

--- sourceeuiwn(kbtu/sf) ---
sourceeuiwn(kbtu/sf)
0.000000      36
NaN            9
87.300003      9
73.599998      9
102.400002     8
Name: count, dtype: int64

--- siteenergyuse(kbtu) ---
siteenergyuse(kbtu)
0.0           18
NaN            5
7226362.5      1
8387933.0      1
72587024.0     1
Name: count, dtype: int64

--- siteenergyusewn(kbtu) ---
siteenergyusewn(kbtu)
0.00          29
NaN            6
2127889.25     2
7456910.00     1
8664479.00     1
Name: count, dtype: int64

--- steamuse(kbtu) ---
steamuse(kbtu)
0.00           3237
NaN               9
2003882.00        1
21566554.00       1
2214446.25        1
Name: count, dtype: int64

--- electricity(kwh) ---
electricity(kwh)
0.000000e+00    14
NaN              9
2.390116e+05     2
3.178414e+05     2
1.156514e+06     1
Name: count, dtype: int64

--- electricity(kbtu) ---
electricity(kbtu)
0.0          14
NaN           9
815508.0      2
1084475.0     2
804194.0      2
Name: count, dtype: int64

--- naturalgas(therms) ---
naturalgas(therms)
0.000000        1258
NaN                9
2268.460205        2
12764.529300       1
51450.816410       1
Name: count, dtype: int64

--- naturalgas(kbtu) ---
naturalgas(kbtu)
0.0          1258
NaN             9
226846.0        2
1276453.0       1
5145082.0       1
Name: count, dtype: int64

--- defaultdata ---
defaultdata
False    3263
True      113
Name: count, dtype: int64

--- comments ---
comments
NaN    3376
Name: count, dtype: int64

--- compliancestatus ---
compliancestatus
Compliant                       3211
Error - Correct Default Data     113
Non-Compliant                     37
Missing Data                      15
Name: count, dtype: int64

--- outlier ---
outlier
NaN             3344
Low outlier       23
High outlier       9
Name: count, dtype: int64

--- totalghgemissions ---
totalghgemissions
0.00    9
NaN     9
3.95    7
4.20    6
5.46    6
Name: count, dtype: int64

--- ghgemissionsintensity ---
ghgemissionsintensity
0.17    99
0.15    99
0.16    96
0.18    86
0.19    78
Name: count, dtype: int64

In [62]:
# Calcul du pourcentage moyen de valeurs manquantes par colonne

df_building_consumption["comments"].value_counts(dropna=False)

comments
NaN    3376
Name: count, dtype: int64

In [60]:
#creation d'un tableau récapitulatif des colonnes de la base de données

summary = pd.DataFrame({
    "dtype": df_building_consumption.dtypes,
    "non_null": df_building_consumption.count(),
    "missing": df_building_consumption.isna().sum(),
    "missing_pct": (
        df_building_consumption.isna().mean() * 100
    ).round(2),
    "n_unique": df_building_consumption.nunique()
})

summary.sort_values("missing_pct", ascending=False)

,dtype,non_null,missing,missing_pct,n_unique
comments,float64,0,3376,100.00,0
outlier,str,32,3344,99.05,2
yearsenergystarcertified,object,119,3257,96.48,65
thirdlargestpropertyusetype,str,596,2780,82.35,44
thirdlargestpropertyusetypegfa,float64,596,2780,82.35,501
secondlargestpropertyusetype,str,1679,1697,50.27,50
secondlargestpropertyusetypegfa,float64,1679,1697,50.27,1352
energystarscore,float64,2533,843,24.97,100
largestpropertyusetypegfa,float64,3356,20,0.59,3122
largestpropertyusetype,str,3356,20,0.59,56
zipcode,float64,3360,16,0.47,55
listofallpropertyusetypes,str,3367,9,0.27,466
electricity(kwh),float64,3367,9,0.27,3352
sourceeuiwn(kbtu/sf),float64,3367,9,0.27,1694
ghgemissionsintensity,float64,3367,9,0.27,511
totalghgemissions,float64,3367,9,0.27,2818
naturalgas(therms),float64,3367,9,0.27,2109
steamuse(kbtu),float64,3367,9,0.27,131
naturalgas(kbtu),float64,3367,9,0.27,2109
sourceeui(kbtu/sf),float64,3367,9,0.27,1648
electricity(kbtu),float64,3367,9,0.27,3351
numberofbuildings,float64,3368,8,0.24,17
siteeui(kbtu/sf),float64,3369,7,0.21,1085
siteenergyusewn(kbtu),float64,3370,6,0.18,3341
siteeuiwn(kbtu/sf),float64,3370,6,0.18,1105
siteenergyuse(kbtu),float64,3371,5,0.15,3354
osebuildingid,int64,3376,0,0.00,3376
propertyname,str,3376,0,0.00,3362
primarypropertytype,str,3376,0,0.00,24
buildingtype,str,3376,0,0.00,8
longitude,float64,3376,0,0.00,2656
latitude,float64,3376,0,0.00,2876
neighborhood,str,3376,0,0.00,19
councildistrictcode,int64,3376,0,0.00,7
taxparcelidentificationnumber,str,3376,0,0.00,3268
state,str,3376,0,0.00,1
city,str,3376,0,0.00,1
address,str,3376,0,0.00,3354
datayear,int64,3376,0,0.00,1
propertygfatotal,int64,3376,0,0.00,3195
propertygfabuilding(s),int64,3376,0,0.00,3193
yearbuilt,int64,3376,0,0.00,113
propertygfaparking,int64,3376,0,0.00,496
numberoffloors,int64,3376,0,0.00,50
defaultdata,bool,3376,0,0.00,2
compliancestatus,str,3376,0,0.00,4

> **Observation :** 

> * Les colonnes `comments` (100 %), `outlier` (99,05 %) et `yearenergystarcertified` (96,48 %) sont presque entièrement vides et seront étudiées afin de déterminer leur intérêt pour la modélisation. 
> * Les variables `secondlargestpropertyusetype` et `thirdlargestpropertyusetype`, ainsi que leurs surfaces associées, présentent également un nombre élevé de valeurs manquantes. En revanche, la majorité des autres variables comporte moins de 1 % de valeurs manquantes.

In [67]:
constant_columns = ["city", "state", "datayear"]

for col in constant_columns:
    print(f"\n--- {col} ---")
    print(df_building_consumption[col].value_counts(dropna=False))

--- city ---
city
Seattle    3376
Name: count, dtype: int64

--- state ---
state
WA    3376
Name: count, dtype: int64

--- datayear ---
datayear
2016    3376
Name: count, dtype: int64

In [65]:
df_building_consumption["state"].value_counts(dropna=False)

state
WA    3376
Name: count, dtype: int64

In [66]:
df_building_consumption["datayear"].value_counts(dropna=False)

datayear
2016    3376
Name: count, dtype: int64

##### **Suppression des colonnes inutilisables**

##### **Statistiques Descriptives**

In [48]:
describe = df_building_consumption.describe().T

describe.style.format(
    lambda x: f"{x:,.2f}".replace(",", " ").replace(".", ",")
)

> **Observation :** 
> * Les statistiques descriptives montrent que le jeu de données contient 3 376 bâtiments. Les variables `datayear`, `city` et `state` sont concernent une seule campagne de collecte réalisée en 2016 à Seattle. 
> * Les caractéristiques physiques des bâtiments présentent une forte variabilité, notamment la surface totale (`propertygfatotal`) et le nombre d'étages (`numberoffloors`). 
> * Les variables de consommation énergétique et d'émissions de gaz à effet de serre suggérent la présence de valeurs extrêmes qui devront être analysées.

In [39]:
df_building_consumption.info()

<class 'pandas.DataFrame'>
RangeIndex: 3376 entries, 0 to 3375
Data columns (total 46 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   osebuildingid                    3376 non-null   int64
 1   datayear                         3376 non-null   int64
 2   buildingtype                     3376 non-null   str
 3   primarypropertytype              3376 non-null   str
 4   propertyname                     3376 non-null   str
 5   address                          3376 non-null   str
 6   city                             3376 non-null   str
 7   state                            3376 non-null   str
 8   zipcode                          3360 non-null   float64
 9   taxparcelidentificationnumber    3376 non-null   str
 10  councildistrictcode              3376 non-null   int64
 11  neighborhood                     3376 non-null   str
 12  latitude                         3376 non-null   float64
 13  longitude                        3376 non-null   float64
 14  yearbuilt                        3376 non-null   int64
 15  numberofbuildings                3368 non-null   float64
 16  numberoffloors                   3376 non-null   int64
 17  propertygfatotal                 3376 non-null   int64
 18  propertygfaparking               3376 non-null   int64
 19  propertygfabuilding(s)           3376 non-null   int64
 20  listofallpropertyusetypes        3367 non-null   str
 21  largestpropertyusetype           3356 non-null   str
 22  largestpropertyusetypegfa        3356 non-null   float64
 23  secondlargestpropertyusetype     1679 non-null   str
 24  secondlargestpropertyusetypegfa  1679 non-null   float64
 25  thirdlargestpropertyusetype      596 non-null    str
 26  thirdlargestpropertyusetypegfa   596 non-null    float64
 27  yearsenergystarcertified         119 non-null    object
 28  energystarscore                  2533 non-null   float64
 29  siteeui(kbtu/sf)                 3369 non-null   float64
 30  siteeuiwn(kbtu/sf)               3370 non-null   float64
 31  sourceeui(kbtu/sf)               3367 non-null   float64
 32  sourceeuiwn(kbtu/sf)             3367 non-null   float64
 33  siteenergyuse(kbtu)              3371 non-null   float64
 34  siteenergyusewn(kbtu)            3370 non-null   float64
 35  steamuse(kbtu)                   3367 non-null   float64
 36  electricity(kwh)                 3367 non-null   float64
 37  electricity(kbtu)                3367 non-null   float64
 38  naturalgas(therms)               3367 non-null   float64
 39  naturalgas(kbtu)                 3367 non-null   float64
 40  defaultdata                      3376 non-null   bool
 41  comments                         0 non-null      float64
 42  compliancestatus                 3376 non-null   str
 43  outlier                          32 non-null     str
 44  totalghgemissions                3367 non-null   float64
 45  ghgemissionsintensity            3367 non-null   float64
dtypes: bool(1), float64(22), int64(8), object(1), str(14)
memory usage: 1.2+ MB

> **Observation :** 
>  * Le jeu de données contient **3 376 observations** et **46 variables**. 
>  * L'aperçu fourni par `info()` met en évidence la présence de valeurs manquantes dans certaines variables, notamment `zipcode`, `numberofbuildings`, `totalghgemissions` et `ghgemissionsintensity`. 
>  * Les types de données sont cohérents avec la nature des variables et ne nécessitent pas de conversion particulière à ce stade.

# Modélisation

### Import des modules

In [40]:
#Selection
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV, 
    cross_validate,
)
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error 
from sklearn.inspection import permutation_importance

#Preprocess
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

#Modèles
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

### Feature Engineering

A réaliser : Enrichir le jeu de données actuel avec de nouvelles features issues de celles existantes.

En règle générale : On utilise la méthode .apply() de Pandas pour créer une nouvelle colonne à partir d'une colonne existante. N'hésitez pas à regarder les exemples dans les chapitres de cours donnés en ressource

In [41]:
# CODE FEATURE ENGINEERING

### Préparation des features pour la modélisation

A réaliser :
* Si ce n'est pas déjà fait, supprimer toutes les colonnes peu pertinentes pour la modélisation.
* Tracer la distribution de la cible pour vous familiariser avec l'ordre de grandeur. En cas d'outliers, mettez en place une démarche pour les supprimer.
* Débarrassez-vous des features redondantes en utilisant une matrice de corrélation de Pearson. Pour cela, utiisez la méthode corr() de Pandas, couplé d'un graphique Heatmap de la librairie Seaborn 
* Réalisez différents graphiques pour comprendre le lien entre vos features et la target (boxplots, scatterplots, pairplot si votre nombre de features numériques n'est pas très élevé).
*  Séparez votre jeu de données en un Pandas DataFrame X (ensemble de feautures) et Pandas Series y (votre target).
* Si vous avez des features catégorielles, il faut les encoder pour que votre modèle fonctionne. Les deux méthodes d'encodage à connaitre sont le OneHotEncoder et le LabelEncoder

In [42]:
# CODE PREPARATION DES FEATURES

### Comparaison de différents modèles supervisés

A réaliser :
* Pour chaque algorithme que vous allez tester, vous devez :
    * Réaliser au préalable une séparation en jeu d'apprentissage et jeu de test via une validation croisée.
    * Si les features quantitatives que vous souhaitez utiliser ont des ordres de grandeur très différents les uns des autres, et que vous utilisez un algorithme de regression qui est sensible à cette différence, alors il faut réaliser un scaling (normalisation) de la donnée au préalable.
    * Entrainer le modèle sur le jeu de Train
    * Prédire la cible sur la donnée de test (nous appelons cette étape, l'inférence).
    * Calculer les métriques de performance R2, MAE et RMSE sur le jeu de train et de test.
    * Interpréter les résultats pour juger de la fiabilité de l'algorithme.
* Vous pouvez choisir par exemple de tester un modèle linéaire, un modèle à base d'arbres et un modèle de type SVM
* Déterminer le modèle le plus performant parmi ceux testés.

In [43]:
# CODE COMPARAISON DES MODELES

### Optimisation et interprétation du modèle

A réaliser :
* Reprennez le meilleur algorithme que vous avez sécurisé via l'étape précédente, et réalisez une GridSearch de petite taille sur au moins 3 hyperparamètres.
* Si le meilleur modèle fait partie de la famille des modèles à arbres (RandomForest, GradientBoosting) alors utilisez la fonctionnalité feature importance pour identifier les features les plus impactantes sur la performance du modèle. Sinon, utilisez la méthode Permutation Importance de sklearn.

In [44]:
# CODE OPTIMISATION ET INTERPRETATION DU MODELE